### ISSUE TITLE
Crash when shift clicking the plus to place a recipe into the ME Pattern Terminal

### ISSUE THREAD

**Issue by yellowbullet100** [NillerMedDild/Enigmatica2#274]
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
When looking at a recipe in JEI while in the ME Pattern Terminal, and then shift clicking the plus, the game will crash rather than fill in the recipe.

**Modpack version (Do not use "latest")**
1.56

**Logs**

If applicable, please upload your crash report, or latest.log to [gist](https://gist.github.com/).
https://gist.github.com/yellowbullet100/b4d0fadc721b88d2906c0104ab5d75c3

**Screenshots**
![ae-shift-click-recipe-crash](https://user-images.githubusercontent.com/5608160/51447569-700c2780-1cd4-11e9-940e-8ca01bcdd306.PNG)

**Additional context**

Was trying to shift click the recipe of Quartz Fiber

**Comment by Kbotei** [comment]
I have also had this happen, though I was only kicked from a server, which did not crash. It has happened with more than just the Quartz Fiber. I also had it happen when shift clicking a Piston  and one or two other recipes. 

I get an error message.

> Internal Exception: java.lang.IllegalArgumentException: Payload may not be larger than 32767 bytes

**Comment by NillerMedDild** [comment]
I'm guessing it's because you're in processing mode instead of crafting, but it shouldn't be happening of course. It should be fixed in a new version, I just need to update :)

**Comment by yellowbullet100** [comment]
@NillerMedDild I upgraded the pack version to 1.57 and tried again, the crash is still there. It happened in the regular crafting mode. [https://drive.google.com/file/d/1RVFpZP9szn2pcw72lNC_hDSBQKGQxKt1/view?usp=sharing](https://drive.google.com/file/d/1RVFpZP9szn2pcw72lNC_hDSBQKGQxKt1/view?usp=sharing)

Hopefully a newer version of AE2 contains a fix.

**Comment by komega13** [comment]
This bug is still there in 2022

**Comment by NielsPilgaard** [comment]
Please provide a crash report.
