### ISSUE TITLE
Game crashes when opening mekanism enrichment factory

### ISSUE THREAD

**Issue by JustTheLegion** [NillerMedDild/Enigmatica2#474]
**Modpack version**
Enigmatica 2 Lite latest
**Can the issue be reproduced?**
Yes
**Logs**
I---- Minecraft Crash Report ----

WARNING: coremods are present:
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.5-1.12.2.jar)
  AppleCore (AppleCore-mc1.12.2-3.2.0.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.64+dev.146.jar)
  AstralCore (astralsorcery-1.12.2-1.10.17.jar)
  RandomPatches (randompatches-1.12.2-1.15.0.2.jar)
  AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-1.5.0-139-universal.jar)
  ForgelinPlugin (Forgelin-1.8.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.57-core.jar)
  PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.2+build43-universal.jar)
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  ColytraLoadingPlugin (colytra-1.12.2-1.2.0.jar)
  Quark Plugin (Quark-r1.5-148.jar)
  FarseekCoreMod (Farseek-1.12-2.3.2.jar)
  PluginLoader (MemoryTester-0.4.2.jar)
Contact their authors BEFORE contacting forge

// I'm sorry, Dave.

Time: 5/22/19 5:00 PM
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at mekanism.common.inventory.container.ContainerFactory$FactoryInputSlot.func_75214_a(ContainerFactory.java:203)
	at vazkii.quark.client.feature.ShowInvalidSlots.renderElements(ShowInvalidSlots.java:63)
	at vazkii.quark.client.feature.ShowInvalidSlots.drawTooltipEvent(ShowInvalidSlots.java:40)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1290_ShowInvalidSlots_drawTooltipEvent_Pre.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.client.config.GuiUtils.drawHoveringText(GuiUtils.java:265)
	at net.minecraftforge.fml.client.config.GuiUtils.drawHoveringText(GuiUtils.java:252)
	at net.minecraft.client.gui.GuiScreen.drawHoveringText(GuiScreen.java:182)
	at net.minecraft.client.gui.GuiScreen.func_146285_a(GuiScreen.java:137)
	at net.minecraft.client.gui.inventory.GuiContainer.func_191948_b(GuiContainer.java:175)
	at mekanism.client.gui.GuiMekanism.func_73863_a(GuiMekanism.java:170)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at mekanism.common.inventory.container.ContainerFactory$FactoryInputSlot.func_75214_a(ContainerFactory.java:203)
	at vazkii.quark.client.feature.ShowInvalidSlots.renderElements(ShowInvalidSlots.java:63)
	at vazkii.quark.client.feature.ShowInvalidSlots.drawTooltipEvent(ShowInvalidSlots.java:40)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1290_ShowInvalidSlots_drawTooltipEvent_Pre.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.client.config.GuiUtils.drawHoveringText(GuiUtils.java:265)
	at net.minecraftforge.fml.client.config.GuiUtils.drawHoveringText(GuiUtils.java:252)
	at net.minecraft.client.gui.GuiScreen.drawHoveringText(GuiScreen.java:182)
	at net.minecraft.client.gui.GuiScreen.func_146285_a(GuiScreen.java:137)
	at net.minecraft.client.gui.inventory.GuiContainer.func_191948_b(GuiContainer.java:175)
	at mekanism.client.gui.GuiMekanism.func_73863_a(GuiMekanism.java:170)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)

-- Screen render details --
Details:
	Screen name: mekanism.client.gui.GuiFactory
	Mouse location: Scaled: (243, 155). Absolute: (486, 396)
	Screen size: Scaled: (512, 354). Absolute: (1024, 708). Scale factor of 2

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['MISHK'/283, l='MpServer', x=-33.26, y=63.00, z=327.87]]
	Chunk stats: MultiplayerChunkCache: 288, 288
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-32,64,256), Chunk: (at 0,4,0 in -2,16; contains blocks -32,0,256 to -17,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 509837 game time, 509837 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 8 total; [EntityBat['Bat'/162, l='MpServer', x=-32.57, y=31.33, z=403.91], EntityWolf['Wolf'/199, l='MpServer', x=9.49, y=70.00, z=256.29], EntitySquid['Squid'/184, l='MpServer', x=-0.70, y=54.71, z=346.30], EntityPlayerSP['MISHK'/283, l='MpServer', x=-33.26, y=63.00, z=327.87], EntityWolf['Wolf'/204, l='MpServer', x=28.50, y=65.00, z=254.61], EntityBat['Bat'/205, l='MpServer', x=31.90, y=24.08, z=271.56], EntityWolf['Wolf'/142, l='MpServer', x=-48.56, y=65.00, z=270.50], EntityMerchant['Emerald Muncher'/143, l='MpServer', x=-56.50, y=63.00, z=304.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Mac OS X (x86_64) version 10.12.6
	Java Version: 1.8.0_211, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 794612680 bytes (757 MB) / 3604480000 bytes (3437 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 3 total; -Xmx4096m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2815 195 mods loaded, 195 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                                | Version                  | Source                                                      | Signature                                |
	|:------ |:--------------------------------- |:------------------------ |:----------------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft                         | 1.12.2                   | minecraft.jar                                               | None                                     |
	| LCHIJA | mcp                               | 9.42                     | minecraft.jar                                               | None                                     |
	| LCHIJA | FML                               | 8.0.99.99                | forge-1.12.2-14.23.5.2815.jar                               | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                             | 14.23.5.2815             | forge-1.12.2-14.23.5.2815.jar                               | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | advancedrocketrycore              | 1                        | minecraft.jar                                               | None                                     |
	| LCHIJA | openmodscore                      | 0.12.2                   | minecraft.jar                                               | None                                     |
	| LCHIJA | foamfixcore                       | 7.7.4                    | minecraft.jar                                               | None                                     |
	| LCHIJA | randompatches                     | 1.12.2-1.15.0.2          | randompatches-1.12.2-1.15.0.2.jar                           | None                                     |
	| LCHIJA | fastbench                         | 1.7.0                    | FastWorkbench-1.12.2-1.7.0.jar                              | None                                     |
	| LCHIJA | actuallyadditions                 | 1.12.2-r146              | ActuallyAdditions-1.12.2-r146.jar                           | None                                     |
	| LCHIJA | baubles                           | 1.5.2                    | Baubles-1.12-1.5.2.jar                                      | None                                     |
	| LCHIJA | actuallybaubles                   | 1.1                      | ActuallyBaubles-1.12-1.1.jar                                | None                                     |
	| LCHIJA | redstoneflux                      | 2.1.0                    | RedstoneFlux-1.12-2.1.0.6-universal.jar                     | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | cofhcore                          | 4.6.2                    | CoFHCore-1.12.2-4.6.2.25-universal.jar                      | None                                     |
	| LCHIJA | ic2                               | 2.8.133-ex112            | industrialcraft-2-2.8.133-ex112.jar                         | de041f9f6187debbc77034a344134053277aa3b0 |
	| LCHIJA | libvulpes                         | 0.4.0.-56                | LibVulpes-1.12.2-0.4.0-56-universal.jar                     | None                                     |
	| LCHIJA | advancedrocketry                  | 1.5.0.-139               | AdvancedRocketry-1.12.2-1.5.0-139-universal.jar             | None                                     |
	| LCHIJA | ctm                               | MC1.12.2-0.3.3.22        | CTM-MC1.12.2-0.3.3.22.jar                                   | None                                     |
	| LCHIJA | appliedenergistics2               | rv6-stable-6             | appliedenergistics2-rv6-stable-6.jar                        | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
	| LCHIJA | bdlib                             | 1.14.3.12                | bdlib-1.14.3.12-mc1.12.2.jar                                | None                                     |
	| LCHIJA | ae2stuff                          | 0.7.0.4                  | ae2stuff-0.7.0.4-mc1.12.2.jar                               | None                                     |
	| LCHIJA | endercore                         | 1.12.2-0.5.57            | EnderCore-1.12.2-0.5.57.jar                                 | None                                     |
	| LCHIJA | crafttweaker                      | 4.1.17                   | CraftTweaker2-1.12-4.1.17.jar                               | None                                     |
	| LCHIJA | mtlib                             | 3.0.6                    | MTLib-3.0.6.jar                                             | None                                     |
	| LCHIJA | modtweaker                        | 4.0.17                   | modtweaker-4.0.17.jar                                       | None                                     |
	| LCHIJA | jei                               | 4.15.0.275               | jei_1.12.2-4.15.0.275.jar                                   | None                                     |
	| LCHIJA | thaumcraft                        | 6.1.BETA26               | Thaumcraft-1.12.2-6.1.BETA26.jar                            | None                                     |
	| LCHIJA | codechickenlib                    | 3.2.2.353                | CodeChickenLib-1.12.2-3.2.2.353-universal.jar               | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | brandonscore                      | 2.4.10                   | BrandonsCore-1.12.2-2.4.10.198-universal.jar                | None                                     |
	| LCHIJA | cofhworld                         | 1.3.0                    | CoFHWorld-1.12.2-1.3.0.6-universal.jar                      | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | thermalfoundation                 | 2.6.2                    | ThermalFoundation-1.12.2-2.6.2.26-universal.jar             | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | draconicevolution                 | 2.3.21                   | Draconic-Evolution-1.12.2-2.3.21.342-universal.jar          | None                                     |
	| LCHIJA | thermalexpansion                  | 5.5.3                    | ThermalExpansion-1.12.2-5.5.3.41-universal.jar              | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | enderio                           | 5.0.43                   | EnderIO-1.12.2-5.0.43.jar                                   | None                                     |
	| LCHIJA | mantle                            | 1.12-1.3.3.49            | Mantle-1.12-1.3.3.49.jar                                    | None                                     |
	| LCHIJA | chisel                            | MC1.12.2-0.2.1.35        | Chisel-MC1.12.2-0.2.1.35.jar                                | None                                     |
	| LCHIJA | enderiointegrationtic             | 5.0.43                   | EnderIO-1.12.2-5.0.43.jar                                   | None                                     |
	| LCHIJA | tconstruct                        | 1.12.2-2.12.0.135        | TConstruct-1.12.2-2.12.0.135.jar                            | None                                     |
	| LCHIJA | p455w0rdslib                      | 2.1.44                   | p455w0rdslib-1.12.2-2.1.44.jar                              | None                                     |
	| LCHIJA | ae2wtlib                          | 1.0.6                    | AE2WTLib-1.12.2-1.0.6.jar                                   | None                                     |
	| LCHIJA | aiimprovements                    | 0.0.1.3                  | AIImprovements-1.12-0.0.1b3.jar                             | None                                     |
	| LCHIJA | akashictome                       | 1.2-12                   | AkashicTome-1.2-12.jar                                      | None                                     |
	| LCHIJA | applecore                         | 3.2.0                    | AppleCore-mc1.12.2-3.2.0.jar                                | None                                     |
	| LCHIJA | appleskin                         | 1.0.9                    | AppleSkin-mc1.12-1.0.9.jar                                  | None                                     |
	| LCHIJA | architecturecraft                 | @VERSION@                | architecturecraft-1.12-3.80.jar                             | None                                     |
	| LCHIJA | astralsorcery                     | 1.10.17                  | astralsorcery-1.12.2-1.10.17.jar                            | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
	| LCHIJA | morphtool                         | 1.2-21                   | Morph-o-Tool-1.2-21.jar                                     | None                                     |
	| LCHIJA | quark                             | r1.5-148                 | Quark-r1.5-148.jar                                          | None                                     |
	| LCHIJA | autoreglib                        | 1.3-28                   | AutoRegLib-1.3-28.jar                                       | None                                     |
	| LCHIJA | backpack                          | 3.0.2                    | backpack-3.0.2-1.12.2.jar                                   | None                                     |
	| LCHIJA | badwithernocookiereloaded         | 1.12.2-3.3.16            | badwithernocookiereloaded-1.12.2-3.3.16.jar                 | None                                     |
	| LCHIJA | betteradvancements                | 0.1.0.77                 | BetterAdvancements-1.12.2-0.1.0.77.jar                      | None                                     |
	| LCHIJA | betterbuilderswands               | 0.13.2                   | BetterBuildersWands-1.12.2-0.13.2.271+5997513.jar           | None                                     |
	| LCHIJA | betterquesting                    | 3.5.299                  | BetterQuesting-3.5.299.jar                                  | None                                     |
	| LCHIJA | blockcraftery                     | 1.12.2-1.2.0             | blockcraftery-1.12.2-1.2.0.jar                              | None                                     |
	| LCHIJA | blockdrops                        | 1.4.0                    | blockdrops-1.12.2-1.4.0.jar                                 | None                                     |
	| LCHIJA | guideapi                          | 1.12-2.1.8-63            | Guide-API-1.12-2.1.8-63.jar                                 | None                                     |
	| LCHIJA | bloodmagic                        | 1.12.2-2.4.0-102         | BloodMagic-1.12.2-2.4.0-102.jar                             | None                                     |
	| LCHIJA | bookshelf                         | 2.3.577                  | Bookshelf-1.12.2-2.3.577.jar                                | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | botania                           | r1.10-361                | Botania r1.10-361.jar                                       | None                                     |
	| LCHIJA | buildinggadgets                   | 2.6.8                    | BuildingGadgets-2.6.8.jar                                   | None                                     |
	| LCHIJA | chameleon                         | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                                    | None                                     |
	| LCHIJA | chiselsandbits                    | 14.32                    | chiselsandbits-14.32.jar                                    | None                                     |
	| LCHIJA | chunkpregenerator                 | 2.1                      | Chunk Pregenerator V1.12-2.1.jar                            | None                                     |
	| LCHIJA | clumps                            | 3.1.2                    | Clumps-3.1.2.jar                                            | None                                     |
	| LCHIJA | colytra                           | 1.2.0                    | colytra-1.12.2-1.2.0.jar                                    | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| LCHIJA | cyclopscore                       | 1.2.0                    | CyclopsCore-1.12.2-1.2.0.jar                                | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| LCHIJA | commoncapabilities                | 2.2.1                    | CommonCapabilities-1.12.2-2.2.1.jar                         | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| LCHIJA | controlling                       | 3.0.6                    | Controlling-3.0.6.jar                                       | None                                     |
	| LCHIJA | cookingforblockheads              | 6.4.70                   | CookingForBlockheads_1.12.2-6.4.70.jar                      | None                                     |
	| LCHIJA | cosmeticarmorreworked             | 1.12.2-v4a               | CosmeticArmorReworked-1.12.2-v4a.jar                        | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
	| LCHIJA | ctgui                             | 1.0.0                    | CraftTweaker2-1.12-4.1.17.jar                               | None                                     |
	| LCHIJA | crafttweakerjei                   | 2.0.3                    | CraftTweaker2-1.12-4.1.17.jar                               | None                                     |
	| LCHIJA | custombackgrounds                 | 1.0                      | CustomBackgrounds-MC1.12-1.1.1.jar                          | None                                     |
	| LCHIJA | custommainmenu                    | 2.0.9                    | CustomMainMenu-MC1.12.2-2.0.9.jar                           | None                                     |
	| LCHIJA | waila                             | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar                                 | None                                     |
	| LCHIJA | stg                               | 1.12.2-1.2.3             | stg-1.12.2-1.2.3.jar                                        | None                                     |
	| LCHIJA | danknull                          | 1.4.43                   | DankNull-1.12-1.4.43.jar                                    | None                                     |
	| LCHIJA | darkutils                         | 1.8.226                  | DarkUtils-1.12.2-1.8.226.jar                                | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | journeymap                        | 1.12.2-5.5.5b5           | journeymap-1.12.2-5.5.5b5.jar                               | None                                     |
	| LCHIJA | defaultoptions                    | 9.2.8                    | DefaultOptions_1.12.2-9.2.8.jar                             | None                                     |
	| LCHIJA | demagnetize                       | 1.12.2-1.0.1             | demagnetize-1.12.2-1.0.1.jar                                | None                                     |
	| LCHIJA | diethopper                        | 1.1                      | diethopper-1.1.jar                                          | None                                     |
	| LCHIJA | ding                              | 1.0.1                    | Ding-1.12.1-1.0.1.jar                                       | None                                     |
	| LCHIJA | dirt2path                         | 1.7.1                    | dirt2path-1.8.0.jar                                         | None                                     |
	| LCHIJA | discordsuite                      | 2.2.4                    | DiscordSuite-2.2.4.jar                                      | None                                     |
	| LCHIJA | enderiobase                       | 5.0.43                   | EnderIO-1.12.2-5.0.43.jar                                   | None                                     |
	| LCHIJA | enderioconduits                   | 5.0.43                   | EnderIO-1.12.2-5.0.43.jar                                   | None                                     |
	| LCHIJA | enderioconduitsappliedenergistics | 5.0.43                   | EnderIO-1.12.2-5.0.43.jar                                   | None                                     |
	| LCHIJA | enderioconduitsopencomputers      | 5.0.43                   | EnderIO-1.12.2-5.0.43.jar                                   | None                                     |
	| LCHIJA | enderioconduitsrefinedstorage     | 5.0.43                   | EnderIO-1.12.2-5.0.43.jar                                   | None                                     |
	| LCHIJA | forestry                          | 5.8.2.387                | forestry_1.12.2-5.8.2.387.jar                               | None                                     |
	| LCHIJA | enderiointegrationforestry        | 5.0.43                   | EnderIO-1.12.2-5.0.43.jar                                   | None                                     |
	| LCHIJA | enderiointegrationticlate         | 5.0.43                   | EnderIO-1.12.2-5.0.43.jar                                   | None                                     |
	| LCHIJA | ftblib                            | 5.4.1.75                 | FTBLib-5.4.1.75.jar                                         | None                                     |
	| LCHIJA | enderiomachines                   | 5.0.43                   | EnderIO-1.12.2-5.0.43.jar                                   | None                                     |
	| LCHIJA | enderiopowertools                 | 5.0.43                   | EnderIO-1.12.2-5.0.43.jar                                   | None                                     |
	| LCHIJA | enderstorage                      | 2.4.5.135                | EnderStorage-1.12.2-2.4.5.135-universal.jar                 | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | immersiveengineering              | 0.12-89                  | ImmersiveEngineering-0.12-89.jar                            | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| LCHIJA | engineersdoors                    | 0.8.0                    | engineers_doors-1.12.2-0.8.0.jar                            | None                                     |
	| LCHIJA | valkyrielib                       | 1.12.2-2.0.19.1          | valkyrielib-1.12.2-2.0.19.1.jar                             | None                                     |
	| LCHIJA | environmentaltech                 | 1.12.2-2.0.19.1          | environmentaltech-1.12.2-2.0.19.1.jar                       | None                                     |
	| LCHIJA | extrabitmanipulation              | 1.12.2-3.4.1             | ExtraBitManipulation-1.12.2-3.4.1.jar                       | None                                     |
	| LCHIJA | extrautils2                       | 1.0                      | extrautils2-1.12-1.9.9.jar                                  | None                                     |
	| LCHIJA | farmingforblockheads              | 3.1.26                   | FarmingForBlockheads_1.12.2-3.1.26.jar                      | None                                     |
	| LCHIJA | farseek                           | 2.3.2                    | Farseek-1.12-2.3.2.jar                                      | None                                     |
	| LCHIJA | fastfurnace                       | 1.3.0                    | FastFurnace-1.12.2-1.3.0.jar                                | None                                     |
	| LCHIJA | fencejumper                       | 1.0.5                    | fencejumper-1.12-1.0.5.jar                                  | None                                     |
	| LCHIJA | foamfix                           | 0.10.5-1.12.2            | foamfix-0.10.5-1.12.2.jar                                   | None                                     |
	| LCHIJA | forgelin                          | 1.8.2                    | Forgelin-1.8.2.jar                                          | None                                     |
	| LCHIJA | ftbutilities                      | 5.3.0.71                 | FTBUtilities-5.3.0.71.jar                                   | None                                     |
	| LCHIJA | fw                                | 1.6.0                    | FullscreenWindowed-1.12-1.6.0.jar                           | None                                     |
	| LCHIJA | immersivepetroleum                | 1.1.9                    | immersivepetroleum-1.12.2-1.1.9.jar                         | None                                     |
	| LCHIJA | immersivetech                     | 1.3.10                   | immersivetech-1.12-1.3.10.jar                               | None                                     |
	| LCHIJA | incontrol                         | 3.9.7                    | incontrol-1.12-3.9.7.jar                                    | None                                     |
	| LCHIJA | mcmultipart                       | 2.5.3                    | MCMultiPart-2.5.3.jar                                       | None                                     |
	| LCHIJA | mekanism                          | 1.12.2-9.7.2.373         | Mekanism-1.12.2-9.7.2.373.jar                               | None                                     |
	| LCHIJA | teslacorelib                      | 1.0.15                   | tesla-core-lib-1.12.2-1.0.15.jar                            | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | industrialforegoing               | 1.12.2-1.12.2            | industrialforegoing-1.12.2-1.12.12-236.jar                  | None                                     |
	| LCHIJA | nuclearcraft                      | 2.16e                    | NuclearCraft-2.16e-1.12.2.jar                               | None                                     |
	| LCHIJA | harvestcraft                      | 1.12.2zb                 | Pam's HarvestCraft 1.12.2zc The 7mm Kidney Stone Update.jar | None                                     |
	| LCHIJA | mcjtylib_ng                       | 3.5.0                    | mcjtylib-1.12-3.5.0.jar                                     | None                                     |
	| LCHIJA | rftools                           | 7.70                     | rftools-1.12-7.70.jar                                       | None                                     |
	| LCHIJA | rustic                            | 1.1.0                    | rustic-1.1.0.jar                                            | None                                     |
	| LCHIJA | integrationforegoing              | 1.12.2-1.9               | IntegrationForegoing-1.12.2-1.9.jar                         | 4ffa87db52cf086d00ecc4853a929367b1c39b5c |
	| LCHIJA | inventorytweaks                   | 1.64+dev.146.2180b27     | InventoryTweaks-1.64+dev.146.jar                            | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LCHIJA | ironchest                         | 1.12.2-7.0.59.842        | ironchest-1.12.2-7.0.59.842.jar                             | None                                     |
	| LCHIJA | jaopca                            | 1.12.2-2.2.8.101         | JAOPCA-1.12.2-2.2.8.101.jar                                 | None                                     |
	| LCHIJA | oredictinit                       | 1.12.2-2.2.1.71          | JAOPCA-1.12.2-2.2.8.101.jar                                 | None                                     |
	| LCHIJA | jehc                              | 1.6.3                    | jehc-1.12.2-1.6.3.jar                                       | None                                     |
	| LCHIJA | jeibees                           | 0.9.0.5                  | jeibees-0.9.0.5-mc1.12.2.jar                                | None                                     |
	| LCHIJA | jeivillagers                      | 1.0                      | jeivillagers-1.12-1.0.2.jar                                 | None                                     |
	| LCHIJA | jepb                              | 1.2.1                    | jepb-1.12-1.2.1.jar                                         | None                                     |
	| LCHIJA | jetif                             | 1.4.1                    | jetif-1.12.2-1.4.1.jar                                      | None                                     |
	| LCHIJA | justenoughpetroleum               | 0.1                      | JustEnoughPetroleum-0.1.jar                                 | None                                     |
	| LCHIJA | jeresources                       | 0.9.0.53                 | JustEnoughResources-1.12.2-0.9.0.53.jar                     | None                                     |
	| LCHIJA | reborncore                        | 3.13.12.447              | RebornCore-1.12.2-3.13.12.447-universal.jar                 | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
	| LCHIJA | justsleep                         | 1.0.0.1                  | JustSleep-1.0.0.1.jar                                       | None                                     |
	| LCHIJA | kleeslabs                         | 5.4.11                   | KleeSlabs_1.12.2-5.4.11.jar                                 | None                                     |
	| LCHIJA | lootcapacitortooltips             | 1.3                      | lootcapacitortooltips-1.3.jar                               | None                                     |
	| LCHIJA | lunatriuscore                     | 1.2.0.42                 | LunatriusCore-1.12.2-1.2.0.42-universal.jar                 | None                                     |
	| LCHIJA | mekanismgenerators                | 1.12.2-9.7.2.373         | MekanismGenerators-1.12.2-9.7.2.373.jar                     | None                                     |
	| LCHIJA | mekanismtools                     | 1.12.2-9.7.2.373         | MekanismTools-1.12.2-9.7.2.373.jar                          | None                                     |
	| LCHIJA | moreoverlays                      | 1.14                     | moreoverlays-1.14-mc1.12.2.jar                              | None                                     |
	| LCHIJA | mousetweaks                       | 2.10                     | MouseTweaks-2.10-mc1.12.2.jar                               | None                                     |
	| LCHIJA | neat                              | 1.4-17                   | Neat 1.4-17.jar                                             | None                                     |
	| LCHIJA | nmsot                             | 1.2.2-mc1.12.2           | NoMobSpawningOnTrees-1.2.2-mc1.12.2.jar                     | None                                     |
	| LCHIJA | nonvflash                         | 1.2.0                    | NoNVFlash-1.12.2-1.2.0.3-universal.jar                      | None                                     |
	| LCHIJA | oldjava                           | 1.0.10                   | OldJavaWarning-1.12.2-1.0.10.jar                            | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | openmods                          | 0.12.2                   | OpenModsLib-1.12.2-0.12.2.jar                               | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| LCHIJA | openblocks                        | 1.8.1                    | OpenBlocks-1.12.2-1.8.1.jar                                 | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| LCHIJA | oreexcavation                     | 1.4.140                  | OreExcavation-1.4.140.jar                                   | None                                     |
	| LCHIJA | placebo                           | 1.6.0                    | Placebo-1.12.2-1.6.0.jar                                    | None                                     |
	| LCHIJA | plustic                           | 7.0.6.1                  | plustic-7.0.6.1.jar                                         | None                                     |
	| LCHIJA | prettybeaches                     | 1.0.4                    | PrettyBeaches_1.12.2-1.0.4.jar                              | None                                     |
	| LCHIJA | projectintelligence               | 1.0.5                    | ProjectIntelligence-1.12.2-1.0.5.21-universal.jar           | None                                     |
	| LCHIJA | questbook                         | 3.1.EXP_NET2-1.12        | questbook-3.1.EXP_NET2-1.12.jar                             | None                                     |
	| LCHIJA | quickleafdecay                    | 1.2.4                    | QuickLeafDecay-MC1.12.1-1.2.4.jar                           | None                                     |
	| LCHIJA | redstonearsenal                   | 2.6.2                    | RedstoneArsenal-1.12.2-2.6.2.17-universal.jar               | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | resourceloader                    | 1.5.3                    | ResourceLoader-MC1.12.1-1.5.3.jar                           | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| LCHIJA | rftoolsdim                        | 5.70                     | rftoolsdim-1.12-5.70.jar                                    | None                                     |
	| LCHIJA | scannable                         | 1.6.3.24                 | Scannable-MC1.12.2-1.6.3.24.jar                             | None                                     |
	| LCHIJA | schematica                        | 1.8.0.169                | Schematica-1.12.2-1.8.0.169-universal.jar                   | None                                     |
	| LCHIJA | solcarrot                         | 1.12.2-1.6.3             | solcarrot-1.12.2-1.6.3.jar                                  | None                                     |
	| LCHIJA | bq_standard                       | 3.4.158                  | StandardExpansion-3.4.158.jar                               | None                                     |
	| LCHIJA | storagedrawers                    | 1.12-5.3.5               | StorageDrawers-1.12.2-5.3.8.jar                             | None                                     |
	| LCHIJA | streams                           | 0.4.5                    | Streams-1.12-0.4.5.jar                                      | None                                     |
	| LCHIJA | supersoundmuffler                 | 1.0.2.10                 | supersoundmuffler-1.12.2-1.0.2.10.jar                       | None                                     |
	| LCHIJA | tcinventoryscan                   | 2.0.10                   | ThaumicInventoryScanning_1.12.2-2.0.10.jar                  | None                                     |
	| LCHIJA | thaumicjei                        | 1.6.0                    | ThaumicJEI-1.12.2-1.6.0-27.jar                              | None                                     |
	| LCHIJA | thaumictinkerer                   | 1.12.2-5.0-353c71c       | thaumictinkerer-1.12.2-5.0-353c71c.jar                      | None                                     |
	| LCHIJA | thermalcultivation                | 0.3.2                    | ThermalCultivation-1.12.2-0.3.2.11-universal.jar            | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | thermaldynamics                   | 2.5.4                    | ThermalDynamics-1.12.2-2.5.4.18-universal.jar               | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | thermalinnovation                 | 0.3.2                    | ThermalInnovation-1.12.2-0.3.2.11-universal.jar             | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | tinkertoolleveling                | 1.12.2-1.1.0.DEV.b23e769 | TinkerToolLeveling-1.12.2-1.1.0.jar                         | None                                     |
	| LCHIJA | tips                              | 1.0.8                    | Tips-1.12.2-1.0.8.jar                                       | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | tipthescales                      | 1.0.4                    | TipTheScales-1.12.2-1.0.4.jar                               | None                                     |
	| LCHIJA | toastcontrol                      | 1.8.0                    | Toast Control-1.12.2-1.8.0.jar                              | None                                     |
	| LCHIJA | tombmanygraves                    | 1.12-4.2.0               | TombManyGraves-1.12-4.2.0.jar                               | None                                     |
	| LCHIJA | torchmaster                       | 1.7.1.74                 | torchmaster_1.12.2-1.7.1.74.jar                             | 5e9a436b366831c8f54a7e80b015784da69278c6 |
	| LCHIJA | torohealthmod                     | 1.12.2-11                | torohealth-1.12.2-11.jar                                    | None                                     |
	| LCHIJA | unloader                          | 1.2.0                    | unloader-1.2.0.jar                                          | None                                     |
	| LCHIJA | universalmodifiers                | 1.12.2-1.0.16.1          | valkyrielib-1.12.2-2.0.19.1.jar                             | None                                     |
	| LCHIJA | villagermarket                    | 1.0.1                    | villager-market-1.12.2-1.0.1.jar                            | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | wanionlib                         | 1.12.2-2.2               | WanionLib-1.12.2-2.2.jar                                    | None                                     |
	| LCHIJA | wawla                             | 2.5.270                  | Wawla-1.12.2-2.5.270.jar                                    | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | wct                               | 3.11.88                  | WirelessCraftingTerminal-1.12.2-3.11.88.jar                 | None                                     |
	| LCHIJA | xnet                              | 1.8.0                    | xnet-1.12-1.8.0.jar                                         | None                                     |
	| LCHIJA | ynot                              | 0.2.3                    | YNot-0.2.3.jar                                              | None                                     |
	| LCHIJA | phosphor-lighting                 | 1.12.2-0.2.2             | phosphor-1.12.2-0.2.2+build43-universal.jar                 | f0387d288626cc2d937daa504e74af570c52a2f1 |
	| LCHIJA | reauth                            | 3.6.0                    | reauth-3.6.0.jar                                            | daba0ec4df71b6da841768c49fb873def208a1e3 |
	| LCHIJA | mysticallib                       | 1.12.2-1.1.1             | mysticallib-1.12.2-1.1.1.jar                                | None                                     |
	| LCHIJA | teslacorelib_registries           | 1.0.15                   | tesla-core-lib-1.12.2-1.0.15.jar                            | None                                     |
	| LCHIJA | unidict                           | 1.12.2-2.9.2             | UniDict-1.12.2-2.9.2.jar                                    | None                                     |
	| LCHIJA | wrapup                            | 1.12-1.1.3               | WrapUp-1.12-1.1.3.jar                                       | None                                     |

	Loaded coremods (and transformers): 
Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.5-1.12.2.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
AppleCore (AppleCore-mc1.12.2-3.2.0.jar)
  squeek.applecore.asm.TransformerModuleHandler
OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
  openmods.core.OpenModsClassTransformer
Inventory Tweaks Coremod (InventoryTweaks-1.64+dev.146.jar)
  invtweaks.forge.asm.ContainerTransformer
AstralCore (astralsorcery-1.12.2-1.10.17.jar)
  
RandomPatches (randompatches-1.12.2-1.15.0.2.jar)
  com.therandomlabs.randompatches.core.RPTransformer
AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-1.5.0-139-universal.jar)
  zmaster587.advancedRocketry.asm.ClassTransformer
ForgelinPlugin (Forgelin-1.8.2.jar)
  
CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  team.chisel.ctm.client.asm.CTMTransformer
IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
EnderCorePlugin (EnderCore-1.12.2-0.5.57-core.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
  com.enderio.core.common.transform.SimpleMixinPatcher
PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.2+build43-universal.jar)
  
LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  lumien.resourceloader.asm.ClassTransformer
ColytraLoadingPlugin (colytra-1.12.2-1.2.0.jar)
  c4.colytra.asm.ElytraTransformer
Quark Plugin (Quark-r1.5-148.jar)
  vazkii.quark.base.asm.ClassTransformer
FarseekCoreMod (Farseek-1.12-2.3.2.jar)
  farseek.core.FarseekClassTransformer
PluginLoader (MemoryTester-0.4.2.jar)
  
	GL info: ' Vendor: 'Intel Inc.' Version: '2.1 INTEL-10.25.19' Renderer: 'Intel HD Graphics 4000 OpenGL Engine'
	OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:FINISHED],[player_render_hook:FINISHED],[horse_null_fix:FINISHED]
	AE2 Version: stable rv6-stable-6 for Forge 14.23.5.2768
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- wailaIntegration (Enabled/Not Forced)

	List of loaded APIs: 
		* actuallyadditionsapi (34) from ActuallyAdditions-1.12.2-r146.jar
		* ae2wtlib|api (1.1) from AE2WTLib-1.12.2-1.0.6.jar
		* AppleCoreAPI (3.2.0) from AppleCore-mc1.12.2-3.2.0.jar
		* appliedenergistics2|API (rv6) from appliedenergistics2-rv6-stable-6.jar
		* Baubles|API (1.4.0.2) from AE2WTLib-1.12.2-1.0.6.jar
		* betteradvancements|API (0.1.0.77) from BetterAdvancements-1.12.2-0.1.0.77.jar
		* BetterQuesting|API (3.2) from BetterQuesting-3.5.299.jar
		* BetterQuesting|API2 (3.1) from BetterQuesting-3.5.299.jar
		* BetterWithModsAPI (Beta 0.6) from AppleSkin-mc1.12-1.0.9.jar
		* bloodmagic-api (2.0.0) from BloodMagic-1.12.2-2.4.0-102.jar
		* BotaniaAPI (93) from Botania r1.10-361.jar
		* Chisel-API (0.0.1) from Chisel-MC1.12.2-0.2.1.35.jar
		* ChiselAPI|Carving (0.0.1) from Chisel-MC1.12.2-0.2.1.35.jar
		* ChiselsAndBitsAPI (14.25.0) from chiselsandbits-14.32.jar
		* cofhapi (2.5.0) from CoFHCore-1.12.2-4.6.2.25-universal.jar
		* commoncapabilities|api (0.0.1) from CommonCapabilities-1.12.2-2.2.1.jar
		* cosmeticarmorreworked|api (1.0.0) from CosmeticArmorReworked-1.12.2-v4a.jar
		* ctm-api (0.1.0) from CTM-MC1.12.2-0.3.3.22.jar
		* ctm-api-events (0.1.0) from CTM-MC1.12.2-0.3.3.22.jar
		* ctm-api-models (0.1.0) from CTM-MC1.12.2-0.3.3.22.jar
		* ctm-api-textures (0.1.0) from CTM-MC1.12.2-0.3.3.22.jar
		* ctm-api-utils (0.1.0) from CTM-MC1.12.2-0.3.3.22.jar
		* DraconicEvolution|API (1.3) from Draconic-Evolution-1.12.2-2.3.21.342-universal.jar
		* enderioapi (4.0.0) from EnderIO-1.12.2-5.0.43.jar
		* enderioapi|addon (4.0.0) from EnderIO-1.12.2-5.0.43.jar
		* enderioapi|capacitor (4.0.0) from EnderIO-1.12.2-5.0.43.jar
		* enderioapi|conduits (4.0.0) from EnderIO-1.12.2-5.0.43.jar
		* enderioapi|farm (4.0.0) from EnderIO-1.12.2-5.0.43.jar
		* enderioapi|redstone (4.0.0) from EnderIO-1.12.2-5.0.43.jar
		* enderioapi|teleport (4.0.0) from EnderIO-1.12.2-5.0.43.jar
		* enderioapi|tools (4.0.0) from EnderIO-1.12.2-5.0.43.jar
		* enderioapi|upgrades (4.0.0) from EnderIO-1.12.2-5.0.43.jar
		* farmingforblockheads|api (1.0) from FarmingForBlockheads_1.12.2-3.1.26.jar
		* ForestryAPI|apiculture (5.0.0) from forestry_1.12.2-5.8.2.387.jar
		* ForestryAPI|arboriculture (4.3.0) from forestry_1.12.2-5.8.2.387.jar
		* ForestryAPI|book (5.8.1) from forestry_1.12.2-5.8.2.387.jar
		* ForestryAPI|circuits (3.1.0) from forestry_1.12.2-5.8.2.387.jar
		* ForestryAPI|climate (5.0.0) from forestry_1.12.2-5.8.2.387.jar
		* ForestryAPI|core (5.7.0) from forestry_1.12.2-5.8.2.387.jar
		* ForestryAPI|farming (5.8.0) from forestry_1.12.2-5.8.2.387.jar
		* ForestryAPI|food (1.1.0) from forestry_1.12.2-5.8.2.387.jar
		* ForestryAPI|fuels (3.0.0) from forestry_1.12.2-5.8.2.387.jar
		* ForestryAPI|genetics (5.7.0) from forestry_1.12.2-5.8.2.387.jar
		* ForestryAPI|gui (5.8.0) from forestry_1.12.2-5.8.2.387.jar
		* ForestryAPI|hives (4.1.0) from forestry_1.12.2-5.8.2.387.jar
		* ForestryAPI|lepidopterology (1.4.0) from forestry_1.12.2-5.8.2.387.jar
		* ForestryAPI|mail (3.1.0) from forestry_1.12.2-5.8.2.387.jar
		* ForestryAPI|modules (5.7.0) from forestry_1.12.2-5.8.2.387.jar
		* ForestryAPI|multiblock (3.0.0) from forestry_1.12.2-5.8.2.387.jar
		* ForestryAPI|recipes (5.4.0) from forestry_1.12.2-5.8.2.387.jar
		* ForestryAPI|storage (5.0.0) from forestry_1.12.2-5.8.2.387.jar
		* ForestryAPI|world (2.1.0) from forestry_1.12.2-5.8.2.387.jar
		* Guide-API|API (2.0.0) from Guide-API-1.12-2.1.8-63.jar
		* ImmersiveEngineering|API (1.0) from ImmersiveEngineering-0.12-89.jar
		* ImmersiveEngineering|ImmersiveFluxAPI (1.0) from ImmersiveEngineering-0.12-89.jar
		* industrialforegoingapi (5) from industrialforegoing-1.12.2-1.12.12-236.jar
		* jeresources|API (0.9.0.53) from JustEnoughResources-1.12.2-0.9.0.53.jar
		* journeymap|client-api (1.4) from journeymap-1.12.2-5.5.5b5.jar
		* journeymap|client-api-display (1.4) from journeymap-1.12.2-5.5.5b5.jar
		* journeymap|client-api-event (1.4) from journeymap-1.12.2-5.5.5b5.jar
		* journeymap|client-api-model (1.4) from journeymap-1.12.2-5.5.5b5.jar
		* journeymap|client-api-util (1.4) from journeymap-1.12.2-5.5.5b5.jar
		* JustEnoughItemsAPI (4.13.0) from jei_1.12.2-4.15.0.275.jar
		* MekanismAPI|core (9.7.2) from Mekanism-1.12.2-9.7.2.373.jar
		* MekanismAPI|energy (9.7.2) from Mekanism-1.12.2-9.7.2.373.jar
		* MekanismAPI|gas (9.7.2) from Mekanism-1.12.2-9.7.2.373.jar
		* MekanismAPI|infuse (9.7.2) from Mekanism-1.12.2-9.7.2.373.jar
		* MekanismAPI|laser (9.7.2) from Mekanism-1.12.2-9.7.2.373.jar
		* MekanismAPI|transmitter (9.7.2) from Mekanism-1.12.2-9.7.2.373.jar
		* MekanismAPI|util (9.0.0) from Mekanism-1.12.2-9.7.2.373.jar
		* MouseTweaks|API (1.0) from MouseTweaks-2.10-mc1.12.2.jar
		* openblocks|api (1.2) from OpenBlocks-1.12.2-1.8.1.jar
		* ProjectEAPI (1.9.4-1.0.0) from p455w0rdslib-1.12.2-2.1.44.jar
		* QuarkAPI (3) from Quark-r1.5-148.jar
		* reborncoreAPI (3.13.12.447) from RebornCore-1.12.2-3.13.12.447-universal.jar
		* reborncoreAPI|Power (3.13.12.447) from RebornCore-1.12.2-3.13.12.447-universal.jar
		* reborncoreAPI|Recipe (3.13.12.447) from RebornCore-1.12.2-3.13.12.447-universal.jar
		* reborncoreAPI|Tile (3.13.12.447) from RebornCore-1.12.2-3.13.12.447-universal.jar
		* redstonefluxapi (2.1.0) from RedstoneFlux-1.12-2.1.0.6-universal.jar
		* SchematicaAPI (1.1) from Schematica-1.12.2-1.8.0.169-universal.jar
		* SchematicaAPI|Events (1.1) from Schematica-1.12.2-1.8.0.169-universal.jar
		* StorageDrawersAPI (2.1.0) from StorageDrawers-1.12.2-5.3.8.jar
		* StorageDrawersAPI|event (2.1.0) from StorageDrawers-1.12.2-5.3.8.jar
		* StorageDrawersAPI|registry (2.1.0) from StorageDrawers-1.12.2-5.3.8.jar
		* StorageDrawersAPI|render (2.1.0) from StorageDrawers-1.12.2-5.3.8.jar
		* StorageDrawersAPI|storage (2.1.0) from StorageDrawers-1.12.2-5.3.8.jar
		* StorageDrawersAPI|storage-attribute (2.1.0) from StorageDrawers-1.12.2-5.3.8.jar
		* Thaumcraft|API (6.0.2) from Thaumcraft-1.12.2-6.1.BETA26.jar
		* valkyrielib.api (1.12.2-2.0.10a) from valkyrielib-1.12.2-2.0.19.1.jar
		* WailaAPI (1.3) from Hwyla-1.8.26-B41_1.12.2.jar
		* wct|api (1.1) from WirelessCraftingTerminal-1.12.2-3.11.88.jar
	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 3.13.12.447
		Runtime Debofucsation 1
		RenderEngine: 0
	Ender IO: No known problems detected.

	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	!!!You are looking at the diagnostics information, not at the crash.       !!!
	!!!Scroll up until you see the line with '---- Minecraft Crash Report ----'!!!
	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

	forestry : Modules have been disabled in the config: Crate
	AE2 Integration: IC2:ON, RC:OFF, MFR:OFF, Waila:ON, InvTweaks:ON, JEI:ON, Mekanism:ON, OpenComputers:OFF, THE_ONE_PROBE:OFF, TESLA:OFF, CRAFTTWEAKER:ON
	Launched Version: forge-14.23.5.2815
	LWJGL: 2.9.2
	OpenGL: Intel HD Graphics 4000 OpenGL Engine GL version 2.1 INTEL-10.25.19, Intel Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
**Issue**
Whenever i open mekanism enrichmnet factory my game crashes.

If this is a feature request, feel free to delete the template.

**Comment by phit** [comment]
you aren't running "latest", this is already fixed

**Comment by NillerMedDild** [comment]
This is fixed in 1.2.8, so I don't know what you think latest is. Also, please never post your crash log in the issue, upload it to something like pastebin and link to that.

**Comment by JustTheLegion** [comment]
I am playing on the latest version (1.2.8) and game is still crashing.

**Comment by NillerMedDild** [comment]
Reinstall in that case, this bug is fixed in 1.2.8
