### ISSUE TITLE
Quest - Got Grout ? - Require Air

### ISSUE THREAD

**Issue by MedianAura** [NillerMedDild/Enigmatica2#520]
**Modpack version**
1.69a

**Can the issue be reproduced?**
Yes

**Logs**
No logs

**Issue**
The requirement for the quest Got Group ? is 128 Air 

![2019-07-20 22_50_03-Window](https://user-images.githubusercontent.com/593229/61586411-2a280300-ab41-11e9-9f77-11d1a9601c39.png)

**Comment by NillerMedDild** [comment]
Huh, that's odd. Thanks for letting me know.

**Comment by NillerMedDild** [comment]
Should be fix in 1.69b :)

**Comment by PradyunS** [comment]
on 1.69b beta, still occurs.

**Comment by NillerMedDild** [comment]
Use the command /bq_admin default load - it only works if cheats are enabled or you're OP.

**Comment by PradyunS** [comment]
ah that worked, thanks :)

**Comment by Noruka** [comment]
Still happends, command does not fix the isssue.

**Comment by NillerMedDild** [comment]
Make sure you're on the latest modpack version, and have rights to use the command. This issue is fixed.

**Comment by Noruka** [comment]
Im on the 1.71 version. Just updated today. Started a Singleplayer world with cheats.

I created a new world in creative and it still has the 128 air. 
![f816a430f205b5b4547010a133a3cf34](https://user-images.githubusercontent.com/44400784/64489798-7a753480-d257-11e9-8128-6887072f42df.png)

**Comment by SPL17SCR33N** [comment]
I can confirm this happens on latest version as well, creative mode doesnt fix it nor using the command posted earlier.

**Comment by NillerMedDild** [comment]
What the actual beep, there are no counts of minecraft:air in the quest file. I guess E2 is using old BQ. My apologies.

**Comment by NillerMedDild** [comment]
I believe to have fixed it now, would one of you mind verifying that it works? I can't launch E2 anymore.

If you should accept, put [this file](https://drive.google.com/open?id=1HLEmWKRYc7GjACEMmZgoi4LkSDCal8-B) in your Enigmatica 2 instance, in the folder `config/betterquesting`, and launch the game like normal.

**Comment by SPL17SCR33N** [comment]
That new config does solve the problem, after running the command posted earlier. Thank you!

**Comment by NillerMedDild** [comment]
Thanks for testing it :D

**Comment by NillerMedDild** [comment]
Update incoming.

**Comment by Sveet** [comment]
This happened to me, I am on 1.72

**Comment by NillerMedDild** [comment]
> Use the command /bq_admin default load - it only works if cheats are enabled or you're OP.
