### ISSUE TITLE
Putting Steam to Use Quest

### ISSUE THREAD

**Issue by TInyTim917** [NillerMedDild/Enigmatica2#605]
**Modpack version**
1.7.5b

**Issue**
This quest will not detect the Turbine Valve. crafting it manually, also craftign it from a AE system. I dropped the items and picked them up. I also relogged. No Change.

**Logs**
[latest.log](https://github.com/NillerMedDild/Enigmatica2/files/4049092/latest.log)

**Comment by NillerMedDild** [comment]
The issue you are experiencing has been fixed I believe, please run the command `/bq_admin default load` to reload your quests.
You need admin rights to run the command. If you're playing singleplayer and don't have cheats enabled, Open to LAN from the Esc menu, with cheats enabled.

**Comment by TInyTim917** [comment]
No change, still does not work. I am playing on a server. I am hosting the server. Please let me know what to try next.

**Comment by NillerMedDild** [comment]
Thanks, I'll have a look asap :)

**Comment by wsstevens** [comment]
I am also experiencing this issue in single-player. Enigmatica 2 version is 1.75b. I did run the "bq_admin default load" command.

**Comment by wsstevens** [comment]
NBT issue maybe? The value has one NBT tag - {mekData:{security:0}}

**Comment by NillerMedDild** [comment]
Yep, like all the other Mekanism quest issues this one is caused by NBT :)

**Comment by TInyTim917** [comment]
Cobble-Sulfur Quest has the same issue.
